### ISSUE TITLE
[Question] Is it possible to also have "in-memory" only get and set of values?

### ISSUE THREAD

**Issue by MostHated** [damphat/kv-bash#9]
Hey there,
    I came across this the other day and it seems like it should fit my need quite well. I am using it to store the values of system stats (temperatures, memory, etc) that I gather from running a script for system monitoring and display. It is much more helpful to be able to run my script once on an interval then kvset the values then just let everything else access that stored values until the script runs it's next interval to update instead having each thing that needs the value run the script for it. 

My question is, is it possible to have a 'mode' in which to run kv-sh, where either some specific key/values (or all, if just doing some of them is not possible) are not saved to disk at all, but instead just stored in memory but can be set and get the same way? Some of these values I have updating once per 10 seconds, some once per 5 seconds, but for temp, I have it update once per second and I can't help but feel that writing a tiny bit of data to disk once per second, while very convenient for my use case, might be a bad idea for my SSD, especially considering there is no need to actually save that data for more than one second anyways.

I thank you for making this tool, and for your consideration,
Thanks,
-MH

**Comment by damphat** [comment]
There is no such 'memory' mode of `kv-bash`, because `kv-bash` is created to save/load variables to/from disk.

So when using `kv-bash` instead of `shell script variables`?
 - you want your values to be **permanent**
 - you want to **shared** values with multiple processes / applications

About your app:
- why not get system stats directly from your app?

**Comment by MostHated** [comment]
I appreciate your reply, I think I have this worked out in a satisfactory way. 

I created a 1MB ramdisk using tmpfs and mounted that to /mnt/rdisk and just have the data save there, so that it's not actually saving to my actual ssd. So far it seems to work well. :+1: 

Thanks,
-MH
